#!/usr/bin/env npx tsx
/**
 * Import Neon series + provincial teams into the Voetbalgazet taxonomy.
 *
 * Dry-run (default):
 *   npx tsx scripts/import-neon-taxonomy.ts
 *   npx tsx scripts/import-neon-taxonomy.ts --dry-run
 *
 * Execute (writes generated files + YAML; optional Convex sync):
 *   CONFIRM_NEON_TAXONOMY_IMPORT=1 npx tsx scripts/import-neon-taxonomy.ts --execute
 *   CONFIRM_NEON_TAXONOMY_IMPORT=1 npx tsx scripts/import-neon-taxonomy.ts --execute --sync-convex
 *
 * Policy:
 * - Readable public keys stay user-facing (never CHP_* / CUP_*).
 * - Signup / preference catalog = provincial competitions only (no cups).
 * - neonSeriesMap includes every Neon series for research SQL.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import {
  applyLegacyTeamKey,
  buildSignupTeams,
  parseAllNeonSeries,
  provincialSignupDivisions,
  type NeonSeriesRow,
  type NeonTeamRow,
  type ParsedProvincialSeries,
  type ParsedSeries,
  type SignupTeamOption,
} from "../convex/lib/neonSeriesNaming";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const execute = process.argv.includes("--execute");
const dryRun = !execute;
const syncConvex = process.argv.includes("--sync-convex");

const GENERATED_TS = path.join(
  root,
  "convex/lib/generated/neonTaxonomyData.ts",
);
const DIVISIONS_YAML = path.join(
  root,
  "apps/web/content/settings/divisions.yaml",
);
const TEAMS_YAML = path.join(root, "apps/web/content/settings/teams.yaml");

async function loadNeon(): Promise<{
  series: NeonSeriesRow[];
  teams: NeonTeamRow[];
}> {
  const url = process.env.NEON_DATABASE_URL?.trim();
  if (!url) {
    throw new Error("NEON_DATABASE_URL is required");
  }
  const pool = new pg.Pool({
    connectionString: url,
    max: 2,
    ssl: { rejectUnauthorized: true },
  });
  try {
    const seriesResult = await pool.query<NeonSeriesRow>(
      `select id, name, age_group, channel from series order by name`,
    );
    const teamsResult = await pool.query<NeonTeamRow>(
      `select st.team_id,
              st.club_id,
              st.club_name,
              st.complement,
              t.display_name,
              st.series_id
       from series_teams st
       join teams t on t.id = st.team_id
       join series s on s.id = st.series_id
       where s.name ~ '^[0-9] Provinciaal'
       order by coalesce(t.display_name, st.club_name), st.team_id`,
    );
    return { series: seriesResult.rows, teams: teamsResult.rows };
  } finally {
    await pool.end();
  }
}

function jsonStringifyStable(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function renderGeneratedTs(args: {
  generatedAt: string;
  allSeries: ParsedSeries[];
  divisions: ParsedProvincialSeries[];
  teams: SignupTeamOption[];
}): string {
  const seriesForMap = args.allSeries.map((entry) => ({
    neonSeriesId: entry.neonSeriesId,
    neonSeriesName: entry.neonSeriesName,
    publicKey: entry.publicKey,
    kind: entry.kind,
  }));
  const divisions = args.divisions.map((d) => ({
    key: d.publicKey,
    label: d.catalogLabel,
    shortLabel: d.shortLabel,
    provinceKey: d.provinceKey,
    provinceLabel: d.provinceLabel,
    level: d.level,
    sortOrder: d.sortOrder,
  }));
  const teams = args.teams.map((t) => ({
    key: t.key,
    label: t.label,
    provinceKey: t.provinceKey,
    divisionKeys: t.divisionKeys,
    neonTeamId: t.neonTeamId,
    neonClubId: t.neonClubId,
  }));

  return `/**
 * AUTO-GENERATED by scripts/import-neon-taxonomy.ts — do not edit by hand.
 * Generated at: ${args.generatedAt}
 *
 * Signup divisions = provincial competitions only (cups excluded).
 * Series map = every Neon series for research SQL.
 */
/* eslint-disable */

export type GeneratedNeonSeriesRef = {
  neonSeriesId: string;
  neonSeriesName: string;
  publicKey: string;
  kind: "provincial" | "cup" | "other";
};

export type GeneratedDivisionOption = {
  key: string;
  label: string;
  shortLabel: string;
  provinceKey: string;
  provinceLabel: string;
  level: number;
  sortOrder: number;
};

export type GeneratedTeamOption = {
  key: string;
  label: string;
  provinceKey: string;
  divisionKeys: readonly string[];
  neonTeamId: string;
  neonClubId: string;
};

export const GENERATED_AT = ${JSON.stringify(args.generatedAt)} as const;

export const generatedNeonSeries = ${jsonStringifyStable(seriesForMap)} as const satisfies readonly GeneratedNeonSeriesRef[];

export const generatedDivisionOptions = ${jsonStringifyStable(divisions)} as const satisfies readonly GeneratedDivisionOption[];

export const generatedTeamOptions = ${jsonStringifyStable(teams)} as const satisfies readonly GeneratedTeamOption[];
`;
}

function renderDivisionsYaml(divisions: ParsedProvincialSeries[]): string {
  const lines = ["items:"];
  for (const d of divisions) {
    lines.push(
      `  - { key: ${d.publicKey}, label: ${yamlScalar(d.catalogLabel)}, provinceKey: ${d.provinceKey}, level: ${d.level}, active: true, sortOrder: ${d.sortOrder} }`,
    );
  }
  return `${lines.join("\n")}\n`;
}

function yamlScalar(value: string): string {
  if (/[:#{}[\],&*?|>!%@`]/.test(value) || value.includes("'")) {
    return JSON.stringify(value);
  }
  if (value.includes(" ") || /^-/.test(value)) {
    return JSON.stringify(value);
  }
  return value;
}

function renderTeamsYaml(teams: SignupTeamOption[]): string {
  const lines = ["items:"];
  for (const team of teams) {
    lines.push(`  - key: ${team.key}`);
    lines.push(`    label: ${yamlScalar(team.label)}`);
    lines.push(
      `    divisionKeys: [${team.divisionKeys.join(", ")}]`,
    );
    lines.push(`    provinceKey: ${team.provinceKey}`);
    lines.push(`    active: true`);
    lines.push(`    aliases: []`);
  }
  return `${lines.join("\n")}\n`;
}

function runConvex(args: string[]): string {
  const result = spawnSync("npx", ["convex", ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    cwd: root,
  });
  if (result.status !== 0) {
    console.error(result.stderr || result.stdout);
    process.exit(result.status ?? 1);
  }
  return result.stdout.trim();
}

function parseConvexJson(stdout: string): unknown {
  const start = stdout.indexOf("{");
  const startArr = stdout.indexOf("[");
  const idx =
    start === -1
      ? startArr
      : startArr === -1
        ? start
        : Math.min(start, startArr);
  if (idx === -1) {
    throw new Error(`Could not parse Convex output:\n${stdout}`);
  }
  return JSON.parse(stdout.slice(idx));
}

function summarize(args: {
  allSeries: ParsedSeries[];
  divisions: ParsedProvincialSeries[];
  teams: SignupTeamOption[];
}): void {
  const cups = args.allSeries.filter((s) => s.kind === "cup").length;
  const other = args.allSeries.filter((s) => s.kind === "other").length;
  const byProvince = new Map<string, string[]>();
  for (const d of args.divisions) {
    const list = byProvince.get(d.provinceKey) ?? [];
    list.push(d.shortLabel);
    byProvince.set(d.provinceKey, list);
  }

  console.log(`Neon series total: ${args.allSeries.length}`);
  console.log(`  provincial (signup): ${args.divisions.length}`);
  console.log(`  cups (mapped, not in selector): ${cups}`);
  console.log(`  other (mapped, not in selector): ${other}`);
  console.log(`Signup teams: ${args.teams.length}`);
  console.log("Short labels by province:");
  for (const [province, labels] of byProvince) {
    console.log(`  ${province}: ${labels.join(", ")}`);
  }

  const chpKeys = [
    ...args.divisions.map((d) => d.publicKey),
    ...args.teams.map((t) => t.key),
    ...args.allSeries.map((s) => s.publicKey),
  ].filter((k) => k.startsWith("CHP_") || k.startsWith("CUP_"));
  if (chpKeys.length > 0) {
    throw new Error(
      `Refusing to emit Neon ids as public keys: ${chpKeys.slice(0, 10).join(", ")}`,
    );
  }
}

async function main(): Promise<void> {
  console.log(dryRun ? "=== DRY RUN ===" : "=== EXECUTE ===");
  const { series, teams: teamRows } = await loadNeon();
  const allSeries = parseAllNeonSeries(series);
  const divisions = provincialSignupDivisions(allSeries);
  const provincialByNeonId = new Map(
    divisions.map((d) => [d.neonSeriesId, d] as const),
  );
  const teams = buildSignupTeams(teamRows, provincialByNeonId).map(
    applyLegacyTeamKey,
  );

  summarize({ allSeries, divisions, teams });

  const generatedAt = new Date().toISOString();
  const generatedTs = renderGeneratedTs({
    generatedAt,
    allSeries,
    divisions,
    teams,
  });
  const divisionsYaml = renderDivisionsYaml(divisions);
  const teamsYaml = renderTeamsYaml(teams);

  console.log(`\nWould write:`);
  console.log(`  ${path.relative(root, GENERATED_TS)} (${generatedTs.length} bytes)`);
  console.log(
    `  ${path.relative(root, DIVISIONS_YAML)} (${divisions.length} divisions)`,
  );
  console.log(`  ${path.relative(root, TEAMS_YAML)} (${teams.length} teams)`);

  if (dryRun) {
    console.log("\nDry-run complete. No files written.");
    console.log(
      "To execute: CONFIRM_NEON_TAXONOMY_IMPORT=1 npx tsx scripts/import-neon-taxonomy.ts --execute [--sync-convex]",
    );
    return;
  }

  if (process.env.CONFIRM_NEON_TAXONOMY_IMPORT !== "1") {
    console.error(
      "Refusing --execute without CONFIRM_NEON_TAXONOMY_IMPORT=1",
    );
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(GENERATED_TS), { recursive: true });
  fs.writeFileSync(GENERATED_TS, generatedTs, "utf8");
  fs.writeFileSync(DIVISIONS_YAML, divisionsYaml, "utf8");
  fs.writeFileSync(TEAMS_YAML, teamsYaml, "utf8");
  console.log("\nWrote generated taxonomy files.");

  if (syncConvex) {
    console.log("\nPreviewing Convex taxonomy sync…");
    const preview = runConvex(["run", "taxonomy:previewTaxonomySyncInternal"]);
    console.log(preview);
    console.log("Preview:", parseConvexJson(preview));
    console.log("\nExecuting Convex taxonomy sync…");
    const syncOut = runConvex(["run", "taxonomy:syncTaxonomyInternal"]);
    console.log(syncOut);
    console.log("Sync:", parseConvexJson(syncOut));
  } else {
    console.log(
      "\nSkipped Convex sync (pass --sync-convex after reviewing files).",
    );
  }

  console.log("\nExecute complete.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
