export const SITE_URL = "https://devoetbalgazet.be";
export const CONSENT_VERSION = "2026-07-16";
/** Default social share image (generated by `app/opengraph-image.tsx`). */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;
export const PRIVACY_EMAIL = "privacy@devoetbalgazet.be";
export const EDITORIAL_EMAIL = "redactie@devoetbalgazet.be";
export const PUBLISHER_NAME = "Anton Verhasselt";
export const PUBLISHER_LINE =
  "Verantwoordelijke uitgever: Anton Verhasselt, Van Duyststraat 60, 2100 Antwerpen";
